---
- include: packages.yml

- name: Restore db snapshot
  copy:
    src: "settings.conf"
    dest: "{{ couchpotato_home_dir }}/settings.conf"
    owner: "couchpotato"
    group: "couchpotato"
    mode: 0755

- name: Install service
  template:
    src: couchpotato.service.j2
    dest: /etc/systemd/system/couchpotato.service
    mode: 0644
  register: couchpotato_service
  notify:
    - reload systemd
    - restart couchpotato
