---
- name: Remove default apt settings
  apt_repository: repo='deb http://http.debian.net/debian jessie main' state=absent

- name: Update default apt settings
  apt_repository: repo='deb http://http.debian.net/debian jessie main non-free contrib' state=present

- name: apt-get update
  apt: update_cache=yes

- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
   - apt-transport-https
   - tzdata
   - unrar
   - sshfs
   - curl
   - multitail
   - mtr
   - socat
   - tmux
   - apticron
   - screen

- name: Upgrade all packages
  apt: upgrade=yes
