---
- name: Remove default apt settings
  apt_repository: repo='deb http://http.debian.net/debian jessie main' state=absent

- name: Update default apt settings
  apt_repository: repo='deb http://http.debian.net/debian jessie main non-free contrib' state=present

- name: apt-get update
  apt: update_cache=yes

- name: Enable https for apt-get
  apt: pkg=apt-transport-https state=latest

- name: Install tzdata
  apt: pkg=tzdata state=latest

- name: Install unrar
  apt: pkg=unrar state=latest

- name: Install sshfs
  apt: pkg=sshfs state=latest
