- name: reload systemd
  shell: systemctl daemon-reload
  when: openvpn_service.changed

- name: restart openvpn
  service: name=openvpn@server.service enabled=yes state=restarted

- name: restart iptables
  service: name=iptables.service enabled=yes state=restarted
