- name: restart deluged
  service: name=deluged.service enabled=yes state=restarted

- name: reload systemd
  shell: systemctl daemon-reload

- name: restart deluge-web
  service: name=deluge-web.service enabled=yes state=restarted
