---
# defaults file for plex-server
plex_version: 0.9.16.6.1993-5089475
plex_arch: amd64
plex_deb_file: 'plexmediaserver_{{ plex_version }}_{{ plex_arch }}.deb'
plex_deb_url: '{{ plex_dl_url }}/{{ plex_deb_file }}'
plex_dl_dir: /opt  #define folder/dir to download plex to and install from
plex_dl_url: 'https://downloads.plex.tv/plex-media-server/{{ plex_version }}'
plex_mount_root: /media  #define the root folder where smb mounts should be created...
