---

- name: 1x.yml | Configures 1x with stuff
  hosts: 1x
  become: True

  roles:
    - { role: common,                   tags: ["common"] }
    - { role: package-includes, tags: ["common"] }
    - { role: acdcli, tags: ["downloader"] }
    #- { role: plexconnect,          tags: ["media"] }
    #- { role: plex-server,          tags: ["media"] }
    - { role: ANXS.hostname, tags: ["common"] }
