---

- name: bender.yml | Configures bender with stuff
  hosts: bender
  become: True

  roles:
    - { role: common,                   tags: ["common"] }
    - { role: package-includes, tags: ["common"] }
    - { role: acd-cli, tags: ["downloader"] }
    - { role: plex-server,          tags: ["media"] }
    #- { role: plexconnect,          tags: ["media"] }
    #- { role: plexpy,          tags: ["media"] }
    - { role: ANXS.hostname, tags: ["common"] }
