---

- name: Configure infosphere with stuff
  hosts: infosphere
  become: True

  roles:
    - { role: common, tags: ["common"] }
    - { role: package-includes, tags: ["common"] }
    - { role: deluged, tags: ["downloader"] }
    - { role: acdcli, tags: ["downloader"] }
    - { role: nzbget, tags: ["downloader"] }
