- name: enable packet forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: install iptables
  apt: pkg=iptables state=latest

- name: setup iptables NAT rules
  shell: "{{ item }}"
  with_items:
    - "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
    - "iptables -A FORWARD -i eth0 -o tun0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
    - "iptables -A FORWARD -i tun0 -o eth0 -j ACCEPT"

- name: Get openvpn logs to STDOUT
  replace: dest=/etc/openvpn/server.conf regexp='^log-append' replace=';log-append'

- name: Install openvpn service
  copy: src=openvpn@server.service dest=/etc/systemd/system/openvpn@server.service mode=0755
  register: openvpn_service
  notify:
    - reload systemd
    - restart openvpn
