---
dependencies:
  -
     role: ANXS.postgresql
     #postgresql_data_root
     postgresql_data_directory: "/media/postgres/{{ postgresql_varlib_directory_name }}/{{postgresql_version}}/{{postgresql_cluster_name}}"
     # XXX: extract this
     postgresql_cluster_reset: true #spotweb_init_db
     postgresql_databases: [
       {
         name: spotweb,
         owner: spotweb,
         uuid_ossp: yes
       }
     ]
     postgresql_users: [
       {
         name: 'spotweb',
         pass: 'spotweb' #spotweb_db_user_password
       }
     ]
     postgresql_user_privileges: [
       {
         name: 'spotweb',
         db: 'spotweb',
         priv: "ALL"
       }
     ]
     postgresql_pg_hba_default:
       - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: '{{ postgresql_default_auth_method }}', comment: '' }
       - { type: local, database: all, user: all, address: '',             method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
       - { type: host,  database: all, user: all, address: '127.0.0.1/32', method: '{{ postgresql_default_auth_method }}', comment: 'IPv4 local connections:' }
       - { type: host,  database: all, user: all, address: '::1/128',      method: '{{ postgresql_default_auth_method }}', comment: 'IPv6 local connections:' }
       - { type: host,  database: all, user: all, address: "{{ ansible_default_ipv4['network'] }}/24", method: '{{ postgresql_default_auth_method }}', comment: 'IPv4 network connections:' }
     tags: ["db"]
  -
    role: geerlingguy.nginx
    nginx_vhosts:
      -
        listen: "58080" #spotweb_port
        server_name: "{{ ansible_default_ipv4['address'] }} 127.0.0.1"
        root: "/opt/spotweb"
        index: "index.php index.html index.htm"
        extra_parameters: |
          location / {
            satisfy any;

            if ($uri !~ "api/"){
              rewrite /api/?$ /spotweb/index.php?page=newznabapi last;
            }
            location ~ \.php$ {
              try_files $uri =404;
              include fastcgi_params;
              fastcgi_pass unix:/var/run/php5-fpm.sock;
              fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            }
          }

  -
    role: geerlingguy.php
    php_webserver_daemon: "nginx"
    php_enable_php_fpm: true
    php_date_timezone: "America/Los_Angeles"
    php_fpm_listen: "/var/run/php5-fpm.sock"
